### ISSUE TITLE
トップページのv-footerの位置について

### ISSUE THREAD

**Issue by sugi511** [watsumi/sake_gram#3]
![スクリーンショット 2021-04-06 20 34 06](https://user-images.githubusercontent.com/1669259/113704699-751fea80-9717-11eb-9b97-2fd985453bee.png)

3カラムで表示されてる時に、アイコンをホバーすると展開するが、それによってv-mainの高さが変わってしまって、その結果v-footerの位置が上下に動いて気になるので動かないようにしたい

**Comment by watsumi** [comment]
@sugi511 
ご指摘ありがとうございます！
v-footerの位置を固定することで対応してみました。
```
.v-footer {
  width: 100%;
  position: fixed;
  bottom: 0;
}
```
プルリクも作成しましたので、お時間あるときにご確認いただければ嬉しいです。
よろしくお願いします。
